// Generated by Haxe 3.4.2
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	console.log(inflector_InflectorStringExtensions.pluralize("asd"));
};
var inflector_InflectorStringExtensions = function() { };
inflector_InflectorStringExtensions.pluralize = function(v) {
	return "" + v + " Foo";
};
Test.main();
})();
